name: frontend_mobile
description: "A new Flutter project for AI Health Share."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  go_router: ^13.2.0
  flutter_secure_storage: ^9.0.0
  video_player: ^2.11.1
  flutter_markdown: ^0.7.7+1
  shared_preferences: ^2.5.5
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  flutter_map_cancellable_tile_provider: ^3.1.1
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.2
  fl_chart: ^1.2.0
  intl: ^0.20.2
  image_picker: ^1.2.2
  http_parser: ^4.1.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false # 🚀 TẠM THỜI TẮT IOS ĐỂ TRÁNH LỖI PHẦN CỨNG WINDOWS
  remove_alpha_ios: true # Tự động dọn dẹp độ trong suốt lỗi file ảnh Apple
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#09090B"
  adaptive_icon_foreground: "assets/images/app_icon.png"