org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=C:/Users/mythp/AppData/Local/Programs/Eclipse Adoptium/jdk-17.0.20.8-hotspot
kotlin.incremental=false
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.builtInKotlin=false
kotlin.jvm.target.validation.mode=warning